import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildAgentPrompt } from './agent';
import { runStep } from './progress';
import { selectedAgentSkills, selectedRepoSkills } from './skill-selection';
import type { AppSurface, RouteId, ScaffoldAnswers } from './types';

const UI_VERSION = '^0.4.8';
const DIST_DIR = path.dirname(fileURLToPath(import.meta.url));
const SKILL_POOL_DIR = path.resolve(DIST_DIR, '..', 'skills');

function titleCase(value: string): string {
  return value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function routeTitle(route: RouteId): string {
  return route === 'new-task' ? 'New Task' : titleCase(route);
}

async function writeFile(root: string, filePath: string, content: string): Promise<void> {
  const absolute = path.join(root, filePath);
  await fs.mkdir(path.dirname(absolute), { recursive: true });
  await fs.writeFile(absolute, content);
}

async function writeJson(root: string, filePath: string, value: unknown): Promise<void> {
  await writeFile(root, filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function routePage(projectName: string, route: RouteId): string {
  const title = routeTitle(route);
  return `import { Badge, Card, CardContent, CardHeader, CardTitle } from '@shipshitdev/ui';

export default function ${title.replace(/\s+/g, '')}Page() {
  return (
    <main className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <Badge>${projectName}</Badge>
          <h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em]">${title}</h1>
        </div>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>${title} route</CardTitle>
        </CardHeader>
        <CardContent className="text-sm leading-6 text-secondary">
          This is the default /${route} workspace. The scaffold agent should shape it around the project scope.
        </CardContent>
      </Card>
    </main>
  );
}
`;
}

function globalsCss(): string {
  return `@import "tailwindcss";
@source "../../../node_modules/@shipshitdev/ui/dist";

:root {
  --bg-primary: #09090b;
  --bg-secondary: #111113;
  --bg-tertiary: #18181b;
  --bg-hover: #27272a;
  --text-primary: #fafafa;
  --text-secondary: #a1a1aa;
  --text-muted: #71717a;
}

@theme {
  --color-border: #30363d;
  --color-border-strong: #484f58;
  --color-accent: #fafafa;
  --color-accent-hover: #d4d4d8;
  --color-accent-foreground: #09090b;
  --color-success: #3fb950;
  --color-warning: #d29922;
  --color-danger: #f85149;
  --color-agent: #58a6ff;
  --color-done: #a855f7;
  --font-sans: "DM Sans", ui-sans-serif, system-ui, sans-serif;
  --font-mono: "JetBrains Mono", "SF Mono", monospace;
}

@utility bg-primary { background-color: var(--bg-primary); }
@utility bg-secondary { background-color: var(--bg-secondary); }
@utility bg-tertiary { background-color: var(--bg-tertiary); }
@utility bg-hover { background-color: var(--bg-hover); }
@utility text-primary { color: var(--text-primary); }
@utility text-secondary { color: var(--text-secondary); }
@utility text-muted { color: var(--text-muted); }

html { color-scheme: dark; }

body {
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(88, 166, 255, 0.18), transparent 32rem),
    radial-gradient(circle at bottom right, rgba(63, 185, 80, 0.12), transparent 28rem),
    var(--bg-primary);
  color: var(--text-primary);
}
`;
}

function appShell(projectName: string, routes: RouteId[]): string {
  const links = routes
    .map(
      (route) =>
        `<a className="rounded-md px-3 py-2 text-sm text-secondary transition hover:bg-hover hover:text-primary" href="/${route}">${routeTitle(route)}</a>`,
    )
    .join('\n          ');

  return `import type { Metadata } from 'next';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import './globals.css';

export const metadata: Metadata = {
  title: '${titleCase(projectName)}',
  description: 'Generated by @shipshitdev/v0',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
            <a className="text-sm font-semibold tracking-[0.2em] text-primary uppercase" href="/overview">
              ${projectName}
            </a>
            <div className="flex flex-wrap items-center gap-1">
              ${links}
            </div>
          </nav>
          <div className="mx-auto max-w-6xl px-6 py-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
`;
}

async function writeNextApp(root: string, surface: 'web' | 'app', answers: ScaffoldAnswers): Promise<void> {
  const appRoot = `apps/${surface}`;
  await writeJson(root, `${appRoot}/package.json`, {
    name: `@${answers.packageName}/${surface}`,
    version: '0.0.1',
    private: true,
    scripts: {
      dev: `next dev -p ${surface === 'web' ? 3000 : 3001}`,
      build: 'next build',
      typecheck: 'tsc --noEmit',
      lint: 'biome check app/',
      clean: 'rm -rf .next out',
    },
    dependencies: {
      '@fontsource/dm-sans': '5.2.8',
      '@shipshitdev/ui': UI_VERSION,
      next: '16.2.4',
      react: '19.2.5',
      'react-dom': '19.2.5',
    },
    devDependencies: {
      '@tailwindcss/postcss': '4.2.4',
      '@types/node': '25.6.0',
      '@types/react': '19.2.14',
      '@types/react-dom': '19.2.3',
      tailwindcss: '4.2.4',
      typescript: '6.0.3',
    },
  });
  await writeFile(root, `${appRoot}/next.config.ts`, `import type { NextConfig } from 'next';\n\nconst config: NextConfig = {};\n\nexport default config;\n`);
  await writeFile(root, `${appRoot}/next-env.d.ts`, `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by @shipshitdev/v0.\n`);
  await writeJson(root, `${appRoot}/tsconfig.json`, {
    extends: '../../tsconfig.json',
    compilerOptions: {
      plugins: [{ name: 'next' }],
      jsx: 'preserve',
      allowJs: true,
      incremental: true,
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  });
  await writeFile(root, `${appRoot}/postcss.config.mjs`, `export default {\n  plugins: {\n    '@tailwindcss/postcss': {},\n  },\n};\n`);
  await writeFile(root, `${appRoot}/app/globals.css`, globalsCss());
  await writeFile(root, `${appRoot}/app/layout.tsx`, appShell(answers.projectName, answers.routes));
  await writeFile(root, `${appRoot}/app/page.tsx`, `import { redirect } from 'next/navigation';\n\nexport default function Home() {\n  redirect('/overview');\n}\n`);
  for (const route of answers.routes) {
    await writeFile(root, `${appRoot}/app/${route}/page.tsx`, routePage(answers.projectName, route));
  }
}

function reactApp(surface: AppSurface, answers: ScaffoldAnswers): string {
  const navItems = answers.routes
    .map((route) => `{ id: '${route}', label: '${routeTitle(route)}' }`)
    .join(',\n  ');
  return `import { Badge, Button, Card, CardContent, CardHeader, CardTitle, cn } from '@shipshitdev/ui';
import { useState } from 'react';

const routes = [
  ${navItems},
] as const;

export function App() {
  const [activeRoute, setActiveRoute] = useState<(typeof routes)[number]['id']>('${answers.routes[0] ?? 'overview'}');
  const active = routes.find((route) => route.id === activeRoute) ?? routes[0];

  return (
    <main className="min-h-screen bg-primary p-6 text-primary">
      <div className="mx-auto max-w-6xl space-y-6">
        <header className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <Badge>${surface}</Badge>
            <h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em]">${answers.projectName}</h1>
          </div>
          <div className="flex flex-wrap gap-2">
            {routes.map((route) => (
              <Button
                key={route.id}
                type="button"
                variant={activeRoute === route.id ? 'secondary' : 'ghost'}
                className={cn(activeRoute === route.id && 'bg-hover text-primary')}
                onClick={() => setActiveRoute(route.id)}
              >
                {route.label}
              </Button>
            ))}
          </div>
        </header>
        <Card>
          <CardHeader>
            <CardTitle>{active.label}</CardTitle>
          </CardHeader>
          <CardContent className="text-sm leading-6 text-secondary">
            ${surface} surface generated by @shipshitdev/v0. Scope: ${answers.scope}
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
`;
}

async function writeReactSurface(root: string, surface: Exclude<AppSurface, 'web' | 'app'>, answers: ScaffoldAnswers): Promise<void> {
  const appRoot = `apps/${surface}`;
  const devPort = surface === 'desktop' ? 3010 : surface === 'mobile' ? 3011 : 3012;
  await writeJson(root, `${appRoot}/package.json`, {
    name: `@${answers.packageName}/${surface}`,
    version: '0.0.1',
    private: true,
    scripts: {
      dev: `vite --host 0.0.0.0 --port ${devPort}`,
      build: 'tsc --noEmit && vite build',
      typecheck: 'tsc --noEmit',
      clean: 'rm -rf dist',
    },
    dependencies: {
      '@fontsource/dm-sans': '5.2.8',
      '@shipshitdev/ui': UI_VERSION,
      '@vitejs/plugin-react': '6.0.1',
      vite: '8.0.10',
      react: '19.2.5',
      'react-dom': '19.2.5',
    },
    devDependencies: {
      '@tailwindcss/vite': '4.2.4',
      '@types/react': '19.2.14',
      '@types/react-dom': '19.2.3',
      tailwindcss: '4.2.4',
      typescript: '6.0.3',
    },
  });
  await writeFile(root, `${appRoot}/index.html`, `<!doctype html>\n<html lang="en">\n  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>${answers.projectName} ${surface}</title></head>\n  <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n`);
  await writeFile(root, `${appRoot}/vite.config.ts`, `import tailwindcss from '@tailwindcss/vite';\nimport react from '@vitejs/plugin-react';\nimport { defineConfig } from 'vite';\n\nexport default defineConfig({\n  plugins: [react(), tailwindcss()],\n});\n`);
  await writeFile(root, `${appRoot}/src/main.tsx`, `import '@fontsource/dm-sans/400.css';\nimport '@fontsource/dm-sans/500.css';\nimport '@fontsource/dm-sans/600.css';\nimport { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './style.css';\n\nconst root = document.getElementById('root');\nif (!root) throw new Error('Missing root element');\n\ncreateRoot(root).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n`);
  await writeFile(root, `${appRoot}/src/App.tsx`, reactApp(surface, answers));
  await writeFile(root, `${appRoot}/src/style.css`, globalsCss().replace('@source "../../../node_modules/@shipshitdev/ui/dist";', '@source "../../../node_modules/@shipshitdev/ui/dist";'));
  await writeJson(root, `${appRoot}/tsconfig.json`, {
    extends: '../../tsconfig.json',
    compilerOptions: {
      jsx: 'react-jsx',
      types: ['vite/client'],
    },
    include: ['src', 'vite.config.ts'],
  });
}

function scopeMarkdown(answers: ScaffoldAnswers): string {
  return `# ${answers.projectName}

## Scope

${answers.scope}

## App Surfaces

${answers.apps.map((app) => `- apps/${app}`).join('\n')}

## Default Routes

${answers.routes.map((route) => `- /${route} - ${routeTitle(route)}`).join('\n')}

## Scaffold Agent

${answers.agent}
`;
}

async function prepareTarget(root: string): Promise<void> {
  await fs.mkdir(root, { recursive: true });
  const existing = (await fs.readdir(root)).filter((entry) => entry !== '.git');
  if (existing.length > 0) {
    throw new Error(`Target directory is not empty: ${root}`);
  }
}

function appDevScripts(apps: readonly AppSurface[]): Record<string, string> {
  return Object.fromEntries(apps.map((app) => [`dev:${app}`, `bun run --cwd apps/${app} dev`]));
}

function appScriptDescription(app: AppSurface): string {
  if (app === 'web') return 'starts the marketing Next.js surface at http://localhost:3000';
  if (app === 'app') return 'starts the app Next.js surface at http://localhost:3001';
  if (app === 'desktop') return 'starts the desktop React surface at http://localhost:3010';
  if (app === 'mobile') return 'starts the mobile React surface at http://localhost:3011';
  return 'starts the extension React surface at http://localhost:3012';
}

function appScriptLines(apps: readonly AppSurface[]): string {
  return apps.map((app) => `- \`bun run dev:${app}\` - ${appScriptDescription(app)}`).join('\n');
}

function startCommand(apps: readonly AppSurface[]): string {
  return apps.includes('web') ? 'bun run dev:web' : `bun run dev:${apps[0] ?? 'web'}`;
}

async function writeWorkspaceFiles(root: string, answers: ScaffoldAnswers): Promise<void> {
  await writeJson(root, 'package.json', {
    name: `@${answers.packageName}/monorepo`,
    private: true,
    packageManager: 'bun@1.3.13',
    workspaces: ['apps/*', 'packages/*'],
    scripts: {
      build: 'turbo run build',
      dev: 'turbo run dev',
      ...appDevScripts(answers.apps),
      typecheck: 'turbo run typecheck',
      lint: 'turbo run lint',
      'deps:update': 'bun update --latest',
      clean: 'turbo run clean',
    },
    devDependencies: {
      '@biomejs/biome': '2.4.12',
      '@types/node': '25.6.0',
      turbo: '2.9.6',
      typescript: '6.0.3',
    },
  });
  await writeJson(root, 'turbo.json', {
    $schema: 'https://turbo.build/schema.json',
    tasks: {
      build: {
        dependsOn: ['^build'],
        outputs: ['dist/**', '.next/**', 'out/**'],
      },
      dev: {
        cache: false,
        persistent: true,
      },
      typecheck: {
        dependsOn: ['^build'],
      },
      lint: {},
      'deps:update': {
        cache: false,
      },
      clean: {
        cache: false,
      },
    },
  });
  await writeJson(root, 'tsconfig.json', {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      jsx: 'react-jsx',
      strict: true,
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true,
      noEmit: true,
      isolatedModules: true,
      types: ['node'],
      ignoreDeprecations: '6.0',
    },
    exclude: ['node_modules', 'dist', '.next', 'out'],
  });
  await writeFile(root, '.gitignore', `node_modules\n.turbo\n.next\ndist\nout\n.env\n.env.*\n!.env.example\n`);
  await writeFile(root, 'README.md', `# ${answers.projectName}\n\nGenerated with \`@shipshitdev/v0\`.\n\n## Start\n\n\`\`\`bash\nbun install\n${startCommand(answers.apps)}\n\`\`\`\n\n## App Scripts\n\n${appScriptLines(answers.apps)}\n\n## Update Dependencies\n\n\`\`\`bash\nbun run deps:update\n\`\`\`\n\n## Agent Workspace\n\n- \`.agents/skills\` - source of truth for selected dev workflow skills\n- \`.agents/memory\` - source of truth for project memory\n- \`.claude/skills\` and \`.claude/memory\` - relative symlinks into \`.agents\`\n- \`.codex/skills\` and \`.codex/memory\` - relative symlinks into \`.agents\`\n- \`skills\` - selected repo workflow skills for PRDs, planning, execution, review, and verification\n\n## Scope\n\n${answers.scope}\n`);
}

async function writeV0Metadata(root: string, answers: ScaffoldAnswers): Promise<void> {
  await writeFile(root, '.v0/scope.md', scopeMarkdown(answers));
  await writeFile(root, '.v0/agent-prompt.md', buildAgentPrompt(answers));
}

async function writePackagesWorkspace(root: string): Promise<void> {
  await writeFile(root, 'packages/.gitkeep', '');
}

async function writeAgentWorkspace(root: string, answers: ScaffoldAnswers): Promise<void> {
  await copySelectedSkills(selectedAgentSkills, answers, path.join(root, '.agents', 'skills'));
  await writeFile(root, '.agents/memory/.gitkeep', '');
  await fs.mkdir(path.join(root, '.claude'), { recursive: true });
  await fs.mkdir(path.join(root, '.codex'), { recursive: true });

  await symlinkOrSkip('../.agents/skills', path.join(root, '.claude', 'skills'));
  await symlinkOrSkip('../.agents/memory', path.join(root, '.claude', 'memory'));
  await symlinkOrSkip('../.agents/skills', path.join(root, '.codex', 'skills'));
  await symlinkOrSkip('../.agents/memory', path.join(root, '.codex', 'memory'));
}

async function writeRepoSkills(root: string, answers: ScaffoldAnswers): Promise<void> {
  await copySelectedSkills(selectedRepoSkills, answers, path.join(root, 'skills'));
}

async function copySelectedSkills(
  selectSkills: (answers: ScaffoldAnswers) => string[],
  answers: ScaffoldAnswers,
  targetRoot: string,
): Promise<void> {
  await fs.mkdir(targetRoot, { recursive: true });
  for (const skill of selectSkills(answers)) {
    await copySkill(skill, targetRoot);
  }
}

async function copySkill(skill: string, targetRoot: string): Promise<void> {
  const source = path.join(SKILL_POOL_DIR, skill);
  const target = path.join(targetRoot, skill);
  await fs.cp(source, target, {
    recursive: true,
    force: true,
    errorOnExist: false,
  });
}

async function symlinkOrSkip(target: string, linkPath: string): Promise<void> {
  try {
    await fs.symlink(target, linkPath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
  }
}

export function scaffoldStepLabels(answers: ScaffoldAnswers): string[] {
  return [
    'Check target directory',
    'Create Bun/Turbo workspace',
    'Write v0 scope and agent prompt',
    'Reserve packages workspace',
    'Create agent skills and memory workspace',
    'Create repo workflow skills',
    ...answers.apps.map((app) =>
      app === 'web' || app === 'app'
        ? `Create apps/${app} Next.js surface`
        : `Create apps/${app} React surface`,
    ),
  ];
}

export async function scaffoldProject(answers: ScaffoldAnswers): Promise<void> {
  const root = answers.targetDir;
  await runStep('Check target directory', () => prepareTarget(root));
  await runStep('Create Bun/Turbo workspace', () => writeWorkspaceFiles(root, answers));
  await runStep('Write v0 scope and agent prompt', () => writeV0Metadata(root, answers));
  await runStep('Reserve packages workspace', () => writePackagesWorkspace(root));
  await runStep('Create agent skills and memory workspace', () => writeAgentWorkspace(root, answers));
  await runStep('Create repo workflow skills', () => writeRepoSkills(root, answers));

  for (const app of answers.apps) {
    if (app === 'web' || app === 'app') {
      await runStep(`Create apps/${app} Next.js surface`, () => writeNextApp(root, app, answers));
    } else {
      await runStep(`Create apps/${app} React surface`, () => writeReactSurface(root, app, answers));
    }
  }
}
